config/routes.rb
# == Route Map
#
#                                   Prefix Verb   URI Pattern                                                                                       Controller#Action
#                                     root GET    /                                                                                                 menu#index
#                           roman_numerals GET    /roman_numerals(.:format)                                                                         roman_numerals#index
#                               properties GET    /properties(.:format)                                                                             properties#index
#                                          POST   /properties(.:format)                                                                             properties#create
#                             new_property GET    /properties/new(.:format)                                                                         properties#new
#                            edit_property GET    /properties/:id/edit(.:format)                                                                    properties#edit
#                                 property PATCH  /properties/:id(.:format)                                                                         properties#update
#                                          PUT    /properties/:id(.:format)                                                                         properties#update
#                                          DELETE /properties/:id(.:format)                                                                         properties#destroy
#                                          GET    /properties/:property_id/images/:attachment_id(.:format)                                          properties#remove_image
#            rails_postmark_inbound_emails POST   /rails/action_mailbox/postmark/inbound_emails(.:format)                                           action_mailbox/ingresses/postmark/inbound_emails#create
#               rails_relay_inbound_emails POST   /rails/action_mailbox/relay/inbound_emails(.:format)                                              action_mailbox/ingresses/relay/inbound_emails#create
#            rails_sendgrid_inbound_emails POST   /rails/action_mailbox/sendgrid/inbound_emails(.:format)                                           action_mailbox/ingresses/sendgrid/inbound_emails#create
#      rails_mandrill_inbound_health_check GET    /rails/action_mailbox/mandrill/inbound_emails(.:format)                                           action_mailbox/ingresses/mandrill/inbound_emails#health_check
#            rails_mandrill_inbound_emails POST   /rails/action_mailbox/mandrill/inbound_emails(.:format)                                           action_mailbox/ingresses/mandrill/inbound_emails#create
#             rails_mailgun_inbound_emails POST   /rails/action_mailbox/mailgun/inbound_emails/mime(.:format)                                       action_mailbox/ingresses/mailgun/inbound_emails#create
#           rails_conductor_inbound_emails GET    /rails/conductor/action_mailbox/inbound_emails(.:format)                                          rails/conductor/action_mailbox/inbound_emails#index
#                                          POST   /rails/conductor/action_mailbox/inbound_emails(.:format)                                          rails/conductor/action_mailbox/inbound_emails#create
#        new_rails_conductor_inbound_email GET    /rails/conductor/action_mailbox/inbound_emails/new(.:format)                                      rails/conductor/action_mailbox/inbound_emails#new
#       edit_rails_conductor_inbound_email GET    /rails/conductor/action_mailbox/inbound_emails/:id/edit(.:format)                                 rails/conductor/action_mailbox/inbound_emails#edit
#            rails_conductor_inbound_email GET    /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                                      rails/conductor/action_mailbox/inbound_emails#show
#                                          PATCH  /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                                      rails/conductor/action_mailbox/inbound_emails#update
#                                          PUT    /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                                      rails/conductor/action_mailbox/inbound_emails#update
#                                          DELETE /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                                      rails/conductor/action_mailbox/inbound_emails#destroy
# new_rails_conductor_inbound_email_source GET    /rails/conductor/action_mailbox/inbound_emails/sources/new(.:format)                              rails/conductor/action_mailbox/inbound_emails/sources#new
#    rails_conductor_inbound_email_sources POST   /rails/conductor/action_mailbox/inbound_emails/sources(.:format)                                  rails/conductor/action_mailbox/inbound_emails/sources#create
#    rails_conductor_inbound_email_reroute POST   /rails/conductor/action_mailbox/:inbound_email_id/reroute(.:format)                               rails/conductor/action_mailbox/reroutes#create
#                       rails_service_blob GET    /rails/active_storage/blobs/redirect/:signed_id/*filename(.:format)                               active_storage/blobs/redirect#show
#                 rails_service_blob_proxy GET    /rails/active_storage/blobs/proxy/:signed_id/*filename(.:format)                                  active_storage/blobs/proxy#show
#                                          GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                                        active_storage/blobs/redirect#show
#                rails_blob_representation GET    /rails/active_storage/representations/redirect/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations/redirect#show
#          rails_blob_representation_proxy GET    /rails/active_storage/representations/proxy/:signed_blob_id/:variation_key/*filename(.:format)    active_storage/representations/proxy#show
#                                          GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format)          active_storage/representations/redirect#show
#                       rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                                       active_storage/disk#show
#                update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                               active_storage/disk#update
#                     rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                                    active_storage/direct_uploads#create

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'menu#index'

  resources :roman_numerals, only: %i[index]

  resources :properties, except: %i[show]
  get 'properties/:property_id/images/:attachment_id', to: 'properties#remove_image'
end

app/models/property.rb
# == Schema Information
#
# Table name: properties
#
#  id         :integer          not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Property < ApplicationRecord
  validates :name, presence: true, allow_blank: false

  has_many_attached :images
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  protect_from_forgery with: :null_session
  before_action :load_property, only: %i[edit]

  def index
    @records = Property.all
  end

  def new
    @property = Property.new
  end

  def create
    service = PropertyService.new(create_params)

    service.create

    if service.success?
      flash[:success] = 'Propriedade criada com sucesso!'
    else
      flash[:error] = service.errors.join(', ')
    end

    redirect_to action: :new
  end

  def edit; end

  def update
    service = PropertyService.new(update_params)

    service.update(record_id)

    if service.success?
      flash[:success] = 'Propriedade alterada com sucesso!'
    else
      flash[:error] = service.errors.join(', ')
    end
    redirect_to action: :edit
  end

  def destroy
    service = PropertyService.new

    service.destroy(record_id)

    if service.success?
      flash[:success] = 'Propriedade excluída com sucesso!'
    else
      flash[:error] = service.errors.join(', ')
    end

    redirect_to action: :index
  end

  def remove_image
    attachment = Property.find(params[:property_id]).images.find(params[:attachment_id])
    attachment.purge

    redirect_back(fallback_location: { action: 'edit', id: params[:property_id] })
  rescue StandardError => e
    flash[:error] = e.message
    redirect_back(fallback_location: { action: 'edit', id: params[:property_id] })
  end

  protected

  def create_params
    params.require(:property).permit(:name, images: [])
  end

  def update_params
    create_params
  end

  def record_id
    params[:id]
  end

  def load_property
    @property = Property.find(record_id)
  end
end

app/views/properties/_form.html.erb
<%= form_with model: @property do |form| %>
  <div class="container mt-5">
    <div class="row">
      <div class="col-6">
        <div class="mb-3">
          <label for="name" class="form-label">Nome</label>
          <%= form.text_field :name, class: "form-control" %>
        </div>
        <div class="mb-3">
          <label for="images" class="form-label">Imagens</label>
          <%= form.file_field :images, multiple: true, accept:'image/*', class: "form-control" %>
        </div>
      </div>

      <div class="col-12">
        <% if @property&.id.present? %>
          <% @property.images.each do |image| %>
            <div style="display: inline-block;">
              <%= image_tag image, style: "width: 200px; margin-right: 5px;" %>
              <div class="d-grid gap-2 mx-2 my-2">
                <%= link_to "Remover", "/properties/#{@property.id}/images/#{image.id}", class: "btn btn-danger btn-sm", method: :delete %>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>

      <div class="col-6">
        <%= render partial: "layouts/flash", flash: flash %>

        <div class="mt-3">
          <button type="submit" class="btn btn-primary">Salvar</button>
          <%= link_to "Voltar", properties_path, class: "btn btn-dark" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/properties/edit.html.erb
<div class="container mt-5">
  <h3>Edição de Propriedade</h3>

  <input name="_method" type="hidden" value="patch" />
  <%= render partial: "form" %>
</div>

app/views/properties/index.html.erb
<div class="container mt-5">
  <h3 style="margin: 0;display: inline-block;">Propriedades</h3>
  <a href="/" class="btn btn-dark mx-3" style="float: right;">Voltar</a>
  <%= link_to "Nova Propriedade", new_property_path, class: "btn btn-primary", style: "float: right;" %>


  <div class="row mt-5">
    <% if @records.length == 0 %>
      <span>Nenhuma propriedade cadastrada até o momento...</span>
    <% end %>
    <% @records.each do |property| %>
      <div class="col-4 mb-5">
        <%= link_to edit_property_path(property) do %>
          <div class="card" style="width: 18rem;">
            <% if property.images[2].present? %>
              <%= image_tag property.images[2], class: "card-img-top" %>
            <% else %>
              <%= image_tag "no_image.png", class: "card-img-top" %>
            <% end %>
            <div class="card-body">
              <h5 class="card-title"><%= property.name %></h5>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/properties/new.html.erb
<div class="container mt-5">
  <h3>Cadastro de Propriedade</h3>

  <%= render partial: "form" %>
</div>